modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="server"
version="4.4.1"
displayName="Cuspiland´s Mod"
credits="Created using MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/server-4-0"
logoFile="logo.png"
authors="THE_GLACIAL, MCreator"
description='''
Random and useful mod for you and your friends
'''

[[dependencies.server]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




